site_name: Wosa Docs
site_description: Official Wosa Documentation
site_author: Wosa.Core.Development

copyright: Copyright; 2019-2021 Wosa Framework

docs_dir: docs
strict: true

theme:
  name: ivory
  custom_dir: page

repo_url: https://github.com/WosaFramework/Docs/
repo_name: GitHub

markdown_extensions:
  - markdown.extensions.attr_list

nav:
    - 'Home' : 'index.md'
    - 'F.A.Q' : 'faq.md'

    - 'UpdateFFX' : 'updateffx.md'

    - 'Installation' :
      - 'How to install' : 'install/install.md'
      - 'Troubleshooting' : 'install/troubleshooting.md'
    
    - 'Scripting' :
      - 'Connector' :
        - 'Setup' : 'connector/setup.md'
        - 'Server Natives' : 'connector/natives_server.md'
        - 'Client Natives' : 'connector/natives_client.md'

      - 'Events' :
        - 'Server Events' : 'events/events_server.md'
        - 'Client Events' : 'events/events_client.md'

      - 'Core' :
        - 'Introduction' : 'core/introduction.md'
        - 'API Functions' : 'core/api.md'
        - 'System Log' : 'core/system_log.md'
        - 'External Scripts' : 'core/external.md'

        - 'Core Natives' :
          - 'Server Natives' : 'core/server_natives.md'
          - 'Client Natives' : 'core/client_natives.md'